# Generated by Django 4.2.3 on 2023-07-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_alter_post_slug_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="static/images/"),
        ),
        migrations.AlterField(
            model_name="page",
            name="wide_picture",
            field=models.ImageField(blank=True, null=True, upload_to="static/images/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/images/"),
        ),
    ]
