# Generated by Django 4.2.3 on 2023-07-11 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_alter_page_picture_alter_page_wide_picture_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_organization",
        ),
    ]
