# Generated by Django 4.2.3 on 2023-07-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_category"),
        ("pages", "0004_remove_post_is_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(blank=True, to="common.category"),
        ),
    ]
