# Generated by Django 4.2.3 on 2023-07-12 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0006_alter_post_category_blockpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowersPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="followers_page", to="pages.page"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers_page",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
